pedantic option cannot be ignored
-pedantic options is not an option that can be ignored.
GCC 6.x and above issued warnings (and hence errors) while building
CNTK:

  error: pedantic is not an option that controls warnings.